import Ajv from "ajv";
import standalone from "ajv/dist/standalone/index.js";
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { resolve } from "node:path";
export function compileSchema() {
  const schema = JSON.parse(
    readFileSync(
      new URL("../schemas/route-pack.schema.json", import.meta.url),
      "utf8",
    ),
  );
  const ajv = new Ajv({
    allErrors: true,
    strict: true,
    code: { source: true, esm: true },
  });
  let source = standalone(ajv, ajv.compile(schema));
  // Ajv emits CommonJS runtime helper references even with ESM exports.
  // Import only these two tiny helpers, not the schema compiler in the browser.
  source = source.replace(
    /const (\w+) = require\("ajv\/dist\/runtime\/(ucs2length|equal)"\)\.default;/g,
    (_, name, helper) =>
      `import ${name}Module from "ajv/dist/runtime/${helper}.js";const ${name} = typeof ${name}Module === "function" ? ${name}Module : ${name}Module.default;`,
  );
  if (source.includes("require("))
    throw new Error("Unexpected Ajv runtime dependency; review generator.");
  return (
    "// Generated by npm run compile:schema. Do not edit.\n" + source + "\n"
  );
}
if (
  process.argv[1] &&
  resolve(process.argv[1]) === fileURLToPath(import.meta.url)
) {
  const target = new URL("../core/route-schema.generated.mjs", import.meta.url);
  const generated = compileSchema();
  if (process.argv.includes("--check")) {
    if (readFileSync(target, "utf8") !== generated)
      throw new Error(
        "Run npm run compile:schema and commit the updated validator.",
      );
  } else writeFileSync(target, generated);
}
